### ISSUE TITLE
not work in windows amd directml

### ISSUE THREAD

**Issue by ibrahemDev** [w-e-w/stable-diffusion-webui-GPU-temperature-protection#4]
hello thanks for this helpful extensions

I got this error #[Error GPU temperature protection] rocm-smi: [WinError 2] The system cannot find the file specified 
on windows 
amd gpu 
directml

I try this method 
[https://superuser.com/a/723574](https://superuser.com/a/723574)
but its like static results
and this method work good for me 
[https://stackoverflow.com/a/62936850](https://stackoverflow.com/a/62936850)

I mad this code,
I hope this code helpful for you I'm not really good with python
`    
    
    import clr # the pythonnet module.

    clr.AddReference(r'C:\\Users\\user\\Downloads\\OpenHardwareMonitor\\OpenHardwareMonitorLib') 

    from OpenHardwareMonitor.Hardware import Computer

    c = Computer()
    c.CPUEnabled = True # get the Info about CPU
    c.GPUEnabled = True # get the Info about GPU
    c.Open()

    gpuname = 'Radeon RX 560X'

    for a in range(0, len(c.Hardware)):

        if gpuname in str(c.Hardware[a].Name):
            for b in range(0, len(c.Hardware[a].Sensors)):
                if "/temperature" in str(c.Hardware[a].Sensors[b].Identifier):
                    print(c.Hardware[a].Sensors[b].get_Value())
`

Thank You

**Comment by w-e-w** [comment]
![image](https://github.com/w-e-w/stable-diffusion-webui-GPU-temperature-protection/assets/40751091/56ce4b40-d1c6-4cb3-8d99-6d3ed5dadb57)
so I suppose windows and Linux are now one ?

**Comment by ibrahemDev** [comment]
I forgot to read the documentation carefully :)

Will AMD GPU be supported on Windows in the future?

**Comment by w-e-w** [comment]
I don't have a AMD card so I can't do it myself ~~(actually I do have an AMD card from 10+ years ago)~~
and [holotap](https://github.com/holotape) the person who made AMD work use linux 
if someone is able to make it work on Windows I will merge the PR

**Comment by ibrahemDev** [comment]
I made it locally and it works perfectly for me 

#### but the requirements:

#### 1. Add OpenHardwareMonitorLib: It only one file OpenHardwareMonitorLib.dll (the user can add it manually in the root of stable-diffusion-webui )

#### 2.  install pythonnet: I think we can make the user add command arg if want using OpenHardwareMonitorLib and using this arg controls for install pythonnet


I think It works on Windows only with .net

I will be happy to add this feature

**Comment by w-e-w** [comment]
> I made it locally and it works perfectly for me

by that I suppose you meant AMD GPU on windows?

depending on how familiar you are with writing extensions
you can either make it into a PR
or you can send me all the information request to achieve the function so I can implement it

I think ideally there should be able to make it so that no extra Library will be installed unless user actually use the required module, this should be totally possible
OpenHardwareMonitorLib.dll it should be a simple matter to download it and extract

stuff should not be placed in webui root, everything aside from assets (like downloaded models) should be contained within the extensions directory
this is one of the rules that one should follow when making extensions

**Comment by ibrahemDev** [comment]
nice I will create PR soon I want to learn python :D

**Comment by ibrahemDev** [comment]
#5
